[package]
name = "real-engine"
version = "0.1.0"
authors = ["Ross Gardiner <ross-public@gmx.com>"]

[[bin]]
name = "engine"
path = "src/main.rs"

[dependencies]
gfx = "0.17.1"
gfx_window_glutin = "0.23.0"
glutin = "0.15"
cgmath = "0.16.1"
gfx_app = "0.7.0"